# -*- coding: utf-8 -*-
"""ML2  Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eqTwc7cEAK1KoFmr7mAU9pJ460kuaRaQ

# **Program 1**
"""

import pandas as pd

data=pd.DataFrame([
    ['Sunny','Warm','Normal','Strong','Warm','Same','Yes'],
    ['Sunny','Warm','High','Strong','Warm','Same','Yes'],
    ['Rainy','Cold','High','Strong','Warm','Change','No'],
    ['Sunny','Warm','High','Strong','Cool','Change','Yes']
    ],
    columns=['Sky','AirTemp','Humidity','Wind','Water','Forecast','EnjoySport'])

print("Dataset:\n",data)

attributes = data.columns[:-1]
target = data.columns[-1]

def find_s(df):
    hypothesis = ['0']*(len(df.columns)-1)
    for i,row in df.iterrows():
        if row[target] == "Yes":
            for j in range(len(hypothesis)):
                if hypothesis[j]=='0':
                    hypothesis[j]=row[j]
                elif hypothesis[j]!=row[j]:
                    hypothesis[j]='?'
    return hypothesis

final_hypothesis=find_s(data)
print("\nMost specific hypothesis (Find-S):",final_hypothesis)


def can_elimination(df):
    S = [['0']*(len(df.columns)-1)]
    G = [['?']*(len(df.columns)-1)]

    for i,row in df.iterrows():
        if row[target]=="Yes":
            G=[g for g in G if all(g[j]=='?'or g[j]==row[j] for j in range(len(attributes)))]
            for j in range(len(attributes)):
                if S[0][j]=='0':
                    S[0][j]=row[j]
                elif S[0][j]!=row[j]:
                    S[0][j]='?'
        else:
            S=[s for s in S if not all(s[j]=='?' or s[j]==row[j] for j in range(len(attributes)))]
            new_G=[]
            for g in G:
                for j in range(len(attributes)):
                    if g[j]=='?':
                        for val in df[attributes[j]].unique():
                            if val!=row[j]:
                                new_hypo=g.copy()
                                new_hypo[j]=val
                                if any(all(s[k]=='?'or s[k]==new_hypo[k] or s[k]=='0' for k in range(len(attributes)))for s in S):
                                    new_G.append(new_hypo)
            G=new_G
    return S, G

S_final, G_final = can_elimination(data)
print("\n Candidate Elimination Results:")
print("S (Most specific boundary):",S_final)
print("G (Most general boundary):",G_final)

"""# **Program 2**"""

!pip install wittgenstein pandas scikit-learn

import pandas as pd
from sklearn.datasets import load_iris
import wittgenstein as lw

iris = load_iris(as_frame=True)
x=iris.data
y=iris.target

# print(iris.feature_names)
# print(iris.target_names)
# print(iris.target)

df = pd.concat([x,y.rename("target")],axis=1)
print("Dataset head:\n", df.head())

model = lw.RIPPER()
model.fit(x,y, pos_class=0)
print("\n===RIPPER Rules ===")
print(model.ruleset_)

df_bin = df.copy()
df_bin['target'] = (df_bin['target'] == 0).astype(int)

attributes = list(x.columns)

def foil_gain(pos_before,neg_before,pos_after,neg_after):
    if pos_after==0:
        return -1e9
    return pos_after * (((pos_after)/(pos_after+neg_after))-((pos_before)/(pos_before+neg_before)))

def foil(df,target_col='target'):
    rules=[]
    pos_total = df[target_col].sum()
    neg_total = len(df)-pos_total

    while pos_total > 0:
        rule=[]
        pos_rem,neg_rem = pos_total, neg_total
        covered = df.copy()

        while neg_rem >0:
            best_gain, best_attr = -1e9, None
            for attr in attributes:
                for val in df[attr].unique():
                    subset = covered[covered[attr]==val]
                    pos_after = subset[target_col].sum()
                    neg_after = len(subset)-pos_after
                    gain = foil_gain(pos_rem,neg_rem,pos_after,neg_after)
                    if gain > best_gain:
                        best_gain, best_attr, best_val, best_subset = gain,attr,val,subset
            if best_attr is None:
                break
            rule.append((best_attr,best_val))
            covered = best_subset
            pos_rem, neg_rem = covered[target_col].sum(),len(covered)-covered[target_col].sum()

        rules.append(rule)
        df = df.drop(covered.index)
        pos_total, neg_total = df[target_col].sum(), len(df)-df[target_col].sum()
    return rules

rules=foil(df_bin)
print("\n=== FOIL Learned Rules (Setosa vs Not) ===")
for conds in rules:
    cond_str = " AND ".join([f"{a}={v}" for a,v in conds])
    print(f"IF {cond_str} THEN class=0")

"""# **Program 3**"""

import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import BaggingClassifier, AdaBoostClassifier

data = load_breast_cancer()
X= pd.DataFrame(data.data, columns=data.feature_names)
y=pd.Series(data.target)
print("Dataset shape:",X.shape)


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42,stratify=y)


bag_model=BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=50,
    random_state=42
)

bag_model.fit(X_train,y_train)
y_pred_bag=bag_model.predict(X_test)

print("=== Bagging Results ===")
print("Accuracy:",accuracy_score(y_test,y_pred_bag))
print("Classification Report:\n",classification_report(y_test,y_pred_bag))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred_bag))


boost_model=AdaBoostClassifier(
    estimator=DecisionTreeClassifier(max_depth=1),
    n_estimators=50,
    random_state=42)

boost_model.fit(X_train,y_train)
y_pred_boost=boost_model.predict(X_test)

print("\n=== AdaBoost Results ===")
print("Accuracy:",accuracy_score(y_test,y_pred_boost))
print("Classification Report:\n",classification_report(y_test,y_pred_boost))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred_boost))

# print(data.feature_names)
# print(data.target_names)
# print(data.target)
# print(len(data.target))

"""## **Program 4**"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

iris = load_iris(as_frame=True)
X=iris.data
print("Dataset shape:",X.shape)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

k=3
kmean= KMeans(n_clusters=k, random_state=42,n_init=10)
cluster = kmean.fit_predict(X_scaled)

X_clustered = X.copy()
X_clustered['Cluster'] = cluster

print("Sample Clustered Dataset\n",X_clustered.head())

plt.figure(figsize=(8,6))
plt.scatter(X_scaled[:,0],X_scaled[:,1],c=cluster,cmap='viridis',s=50)
plt.scatter(kmean.cluster_centers_[:,0],kmean.cluster_centers_[:,1],c='red',s=200, label="centroids")
plt.title('K-Means Clustering Iris')
plt.xlabel("Featur 1 (scaled)")
plt.ylabel("Feature 2 (scaled)")
plt.legend()
plt.show()

